import "@/styles/globals.css";
import Head from "next/head";
import "../../components/MultiStepProgressBar/MultiStepProgressBar.css";

export default function App({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Truffle</title>
				<meta name="truffle" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} />
		</>
	);
}
